site: jessu.run
title: jessu.run
greetings: Hi 👋
description: >+
  I'm a Senior Infrastructure Security Engineer focussed on infrastructure engineering, ops, 
  and software security. I have strong experience both contributing to and leading projects spanning full stack 
  development, application infrastructure, security engineering, and observability. 

  If your team is looking for an additional experienced Platform Security Engineer, Infrastructure Security Engineer, 
  or Security SRE to scale and secure your services please feel free to reach out via LinkedIn. If you want to know 
  more about the stuff I'm working on, let's chat!
lang: en-US
timezone: Europe/Rome
repo: https://github.com/Frituurpanda/frituurpanda.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Frituurpanda
  bio: Security engineer with a lengthy background in Software Engineering
  userpicture:
  username: Frituurpanda # general username
  github: Frituurpanda # github username
  email: carlojessurun@email.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# LOCAL DEV SETTINGS
#url: "http://localhost:4000" #
#baseurl: "" #

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false
