# Site settings
title: StackSecurity
description: >- 
  StackSecurity - Staff Security Engineer @ TRM Labs
lang: en-US
timezone: Europe/Amsterdam
repo: https://github.com/Frituurpanda/frituurpanda.github.io
mode: dark

# Profile settings
author:
  name: StackSecurity
  bio: >- # tell to the world
    Hello everyone 👋,
    I'm Carlo, and I'm a Staff Security Engineer @ TRM Labs. I'm focussed on the intersection between cloud native security and scaling infrastructure into massive systems. 
    In my spare time I do a lot of sport climbing, bouldering and running. I'm using this space to gather my thoughts and share some knowledge on my daily struggles. 

  username: Frituurpanda
  github: Frituurpanda
  twitter: Frituurpanda
  avatar: /assets/img/avatar.jpg

# URL settings
url: "https://jessu.run"
baseurl:
permalink: /:title/
google_analytics: UA-130203748-1

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - CHANGELOG.md
  - node_modules

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
